name: Update AntiFilter List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Устанавливаем необходимые пакеты
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl sed

      # 2. Загружаем репозиторий
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 3. Скачиваем и обрабатываем данные
      - name: Process sites
        run: |
          echo "payload:" > processed_antifilter.yaml
          curl -s "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked-all.txt" | \
            grep -v '^#' | \
            sed -e 's/domain://g' -e 's/^[[:space:]]*//' -e '/^$/d' | \
            while read -r line; do
              echo "  - DOMAIN,$line" >> processed_antifilter.yaml
            done

      # 4. Проверяем результат
      - name: Validate output
        run: |
          echo "Первые 5 строк результата:"
          head -n 6 processed_antifilter.yaml
          echo "Всего строк: $(wc -l < processed_antifilter.yaml)"

      # 5. Коммитим и пушим
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add processed_antifilter.yaml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M UTC')"
          git pull --ff-only
          git push origin HEAD:main
