name: Update AntiFilter List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Права на запись в репозиторий

    steps:
      # 1. Загружаем репозиторий
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      # 2. Скачиваем, обрабатываем и чистим данные
      - name: Process sites
        run: |
          # Скачиваем список и удаляем "domain:" из каждой строки
          echo "payload:" > processed_antifilter.yaml
          curl -s "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked-all.txt" | \
            grep -v '^#' | \                          # Игнорируем комментарии
            sed 's/domain://g' | \                    # Удаляем "domain:"
            while read -r line; do
              if [ -n "$line" ]; then
                echo "  - DOMAIN,${line}" >> processed_antifilter.yaml
              fi
            done

      # 3. Коммитим и пушим изменения
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add processed_antifilter.yaml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M UTC')"
          git pull --ff-only
          git push origin HEAD:main
