name: Update AntiFilter List

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Process blocklist
        run: |
          curl -s -o raw.txt "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked-all.txt"
          grep -v '^#' raw.txt | sed -E 's/^[[:space:]]*//g; s/domain://gi' | awk 'NF' > cleaned.txt
          echo "payload:" > processed_antifilter.yaml
          while read -r line; do
            echo "  - DOMAIN,$line" >> processed_antifilter.yaml
          done < cleaned.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Настраиваем Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Принудительно обновляем ветку
          git fetch origin main
          git reset --hard origin/main
          
          # Коммитим изменения
          git add processed_antifilter.yaml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M UTC')"
          
          # Пушим с принудительным обновлением
          git push --force-with-lease origin HEAD:main
