name: Update Processed List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Process sites
        run: |
          echo "payload:" > processed_antifilter.yaml
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/refs/heads/release/antifilter-download.txt | while read -r line; do
            if [ -n "$line" ]; then
              echo "  - DOMAIN,$line" >> processed_sites.txt
            fi
          done
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add processed_sites.txt
          git commit -m "Auto-update processed sites list"
          git push
