name: Update Blocklists to Export Branch

on:
  schedule:
    - cron: "0 3,9,15,21 * * *"  # 4 раза в день
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout export branch
        uses: actions/checkout@v4
        with:
          ref: export
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Process blocklists
        run: |
          # Функция обработки
          process_list() {
            local url=$1
            local output=$2
            
            echo "🔄 Processing $output from $url"
            curl -sSf "$url" | \
              grep -v '^#' | \
              sed -E 's/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d; s/^domain://i' | \
              sort -u > cleaned.tmp
            
            echo "payload:" > "$output"
            if [ -s cleaned.tmp ]; then
              while read -r line; do
                echo "  - DOMAIN,$line" >> "$output"
              done < cleaned.tmp
            else
              echo "  # No valid domains found" >> "$output"
            fi
            rm -f cleaned.tmp
          }

          # Обработка всех списков
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/antifilter-download-community.txt" "antifilter-community.yaml"
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/antifilter-download.txt" "antifilter.yaml"
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/refilter.txt" "refilter.yaml"
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked-all.txt" "ru-blocked-all.yaml"
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked-all.txt" "ru-blocked.yaml"
          process_list "https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/win-spy.txt" "win-spy.yaml"

      - name: Commit and push to export branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Проверяем изменения
          if [ -z "$(git status --porcelain)" ]; then
            echo "🔄 No changes detected"
            exit 0
          fi
          
          git add *.yaml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push origin export

      - name: Create Pull Request (if needed)
        if: success()
        run: |
          # Создаем PR из export в main (если нужно)
          gh pr create \
            --head export \
            --base main \
            --title "Automatic export update" \
            --body "Automatically generated export files" \
            --label automated || echo "PR creation skipped"
